# SPDX-FileCopyrightText: 2020-2025 Laurent Montel <montel@kde.org>
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/json-validation.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/cppcheck.yml
      - /gitlab-templates/clang-format.yml
      - /gitlab-templates/windows-qt6.yml
